version: 2.1

orbs:
  rn: react-native-community/react-native@7.1.0
  windows: circleci/windows@2.4.0

jobs:
  checkout_code:
    executor: rn/linux_js
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: .

  verify:
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install node modules for package
          command: cd package && npm install
      - run:
          name: Install node modules for example app
          command: cd example && npm install
      - run:
          name: Lint JS Code (ESLint)
          command: cd package && npx eslint src
      - run:
          name: Lint Example app JS code (ESLint)
          command: cd example && npx eslint .

  test:
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install node modules for package
          command: cd package && npm install
      - run:
          name: Run unit tests with Jest
          command: cd package && npx jest

  build_example_windows:
    executor:
      name: windows/default
      shell: powershell
    steps:
      - checkout
      - run:
          name: Install examples
          command: cd src; npm install; cd ../example; npm install
      - run:
          name: "Restore NuGet packages for Components"
          command: nuget restore .\example\windows\SliderTestWindows.sln
      - run:
          name: "Restore .NET dependencies"
          command: msbuild -t:restore .\example\windows\SliderTestWindows.sln
      - run:
          name: Build example Windows
          command: cd example; npx react-native run-windows --no-packager --no-launch --arch x64 --logging --no-deploy

  build_example_ios:
    executor: rn/macos
    steps:
      - checkout
      - run:
          name: Install deps
          command: cd src && npm install && cd ../example && npm install
      - run:
          name: Install Pods
          command: cd example && npx pod-install
      - run:
          name: Build the iOS example project
          command: cd example/ios && export RCT_NO_LAUNCH_PACKAGER=true && xcodebuild -workspace example.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 11' -scheme example -parallelizeTargets -configuration Debug -derivedDataPath build  -UseModernBuildSystem=YES

workflows:
  slider-full-ci:
    jobs:
      - checkout_code
      - verify:
          requires:
            - checkout_code
      - test:
          requires:
            - verify
      - build_example_windows:
          requires:
            - verify
      - rn/android_build:
          name: build_android_debug
          project_path: "example/android"
          build_type: debug
          requires:
            - verify
      - build_example_ios:
          requires:
            - verify
