version: 2.1

orbs:
  rn: react-native-community/react-native@5.5.0
  windows: circleci/windows@2.4.0
  android: circleci/gradle@2.2.0

jobs:
  checkout_code:
    executor: rn/linux_js
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: .
  analyse:
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: .
      - rn/yarn_install
      - run:
          name: Lint JS Code (ESLint)
          command: yarn run validate:eslint
      - run:
          name: Flow
          command: yarn run validate:flow
      - run:
          name: Jest
          command: yarn run test:jest
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "src/package.json"}}
          paths:
              - node_module
              - src/node_modules
              - example/node_modules

  build_example_ios:
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: .
      - rn/yarn_install
      - run:
          name: Build example iOS
          command: cd example && npx react-native run-ios

  build_example_android:
    executor:
      name: android/default
    steps:
      - checkout
      - run:
          name: Install
          command: yarn install --frozen-lockfile
      - run:
          name: Install examples
          command: cd example && yarn install --frozen-lockfile
      - run:
          name: Build example Android
          command: cd example && npx react-native run-android

  build_example_windows:
    executor:
      name: windows/default
      shell: powershell
    steps:
      - checkout
      - run:
          name: Install
          command: yarn install --frozen-lockfile
      - run:
          name: Install examples
          command: cd example; yarn install --frozen-lockfile
      - run:
          name: "Restore NuGet packages for Components"
          command: nuget restore .\example\windows\SliderTestWindows.sln
      - run:
          name: "Restore .NET dependencies"
          command: msbuild -t:restore .\example\windows\SliderTestWindows.sln
      - run:
          name: Build example Windows
          command: cd example; npx react-native run-windows --no-packager --no-launch --arch x64 --logging --no-deploy

  # To be uncommented as a part of https://github.com/react-native-community/react-native-slider/issues/34
  # publish:
  #   executor: rn/linux_js
  #   steps:
  #     - attach_workspace:
  #         at: .
  #     - rn/yarn_install
  #     - run:
  #         name: Publish to NPM
  #         command: yarn ci:publish

workflows:
  test:
    jobs:
      - checkout_code
      - analyse:
          requires:
            - checkout_code
      - build_example_windows:
          requires:
            - analyse

      # Build the Android app in debug mode
      - rn/android_build:
          name: build_android_debug
          project_path: "example/android"
          build_type: "debug"
          requires:
            - analyse

      # Build the iOS app in release mode and do not run tests
      - rn/ios_build:
          name: build_ios_release
          project_path: "example/ios/example.xcodeproj"
          device: "iPhone 12"
          build_configuration: "Release"
          yarn_cache_folder: ~/.cache/yarn
          scheme: "example"
          requires:
            - analyse

      # - publish:
      #     requires:
      #       - analyse
      #       - rn/android_test
      #       - rn/ios_build_and_test
      #     filters:
      #       branches:
      #         only: master
