version: 2.1

orbs:
  rn: react-native-community/react-native@5.5.0
  windows: circleci/windows@2.4.0

jobs:
  checkout_code:
    executor: rn/linux_js
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: .
  analyse:
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: .
      - rn/yarn_install
      - run:
          name: Lint JS Code (ESLint)
          command: yarn run validate:eslint
      - run:
          name: Flow
          command: yarn run validate:flow
      - run:
          name: Jest
          command: yarn run test:jest

  build_example_windows:
    executor:
      name: windows/default
      shell: powershell
    steps:
      - checkout
      - run:
          name: Install
          command: yarn install --frozen-lockfile
      - run:
          name: Install examples
          command: cd example; yarn install --frozen-lockfile
      - run:
          name: "Restore NuGet packages for Components"
          command: nuget restore .\example\windows\SliderTestWindows.sln
      - run:
          name: "Restore .NET dependencies"
          command: msbuild -t:restore .\example\windows\SliderTestWindows.sln
      - run:
          name: Build example Windows
          command: cd example; npx react-native run-windows --no-packager --no-launch --arch x64 --logging --no-deploy

  # To be uncommented as a part of https://github.com/react-native-community/react-native-slider/issues/34
  # publish:
  #   executor: rn/linux_js
  #   steps:
  #     - attach_workspace:
  #         at: .
  #     - rn/yarn_install
  #     - run:
  #         name: Publish to NPM
  #         command: yarn ci:publish

workflows:
  test:
    jobs:
      - checkout_code
      - analyse:
          requires:
            - checkout_code
      - rn/android_build:
          name: build_android_debug
          project_path: "example/android"
          build_type: debug
          requires:
            - analyse
      - rn/ios_build_and_test:
          project_path: "example/ios/example.xcworkspace"
          derived_data_path: "example/ios/build"
          device: "iPhone X"
          build_configuration: "Release"
          scheme: "example"
          detox_configuration: "ios.sim.release"
          detox_loglevel: "trace"
          requires:
            - analyse
      # - publish:
      #     requires:
      #       - analyse
      #       - rn/android_test
      #       - rn/ios_build_and_test
      #     filters:
      #       branches:
      #         only: master
